Repository Design-Study-Group/BobHub-BE, pull requests merged in 2025-09, with the labels that each got.

#55 [Refactor] 토큰 핸들링 로직 수정
  src/main/java/com/bobhub/_core/config/SecurityConfig.java
  src/main/java/com/bobhub/_core/exception/ErrorCode.java
  src/main/java/com/bobhub/_core/exception/SuccessCode.java
  src/main/java/com/bobhub/_core/jwt/JwtAuthenticationFilter.java
  src/main/java/com/bobhub/_core/jwt/JwtTokenProvider.java
  src/main/java/com/bobhub/_core/utils/ApiUtils.java
  src/main/java/com/bobhub/auth/controller/AuthController.java
  src/main/java/com/bobhub/auth/service/AuthService.java
Labels: refactor

#56 Fix: updated prod logging level
  src/main/resources/application-prod.yml
Labels: fix

#58 [Feat] 회원정보 수정 기능 업데이트
  src/main/java/com/bobhub/user/controller/UserController.java
  src/main/java/com/bobhub/user/dto/UserProfileUpdateDto.java
  src/main/java/com/bobhub/user/mapper/UserMapper.java
  src/main/java/com/bobhub/user/service/UserService.java
  src/main/resources/mappers/UserMapper.xml
Labels: feature

#62 [Feat] 챗봇 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/bobhub/_core/config/GeminiConfig.java
  src/main/java/com/bobhub/_core/config/WebSocketConfig.java
  src/main/java/com/bobhub/_core/config/WebSocketSecurityConfig.java
  src/main/java/com/bobhub/chatbot/ChatbotService.java
  src/main/java/com/bobhub/chatbot/ChatbotWebSocketController.java
  src/main/resources/application.yml
  src/main/resources/prompts/chat-prompt.st
Labels: feature

#63 Feat 59
  build.gradle
  src/main/java/com/bobhub/chat/WebSockChatHandler.java
  src/main/java/com/bobhub/chat/WebSockConfig.java
  src/main/java/com/bobhub/chat/controller/ChatController.java
  src/main/java/com/bobhub/chat/domain/Chat.java
  src/main/java/com/bobhub/chat/domain/ChatMessage.java
  src/main/java/com/bobhub/chat/domain/ChatRoom.java
  src/main/java/com/bobhub/chat/dto/ChatMessageResponse.java
  src/main/java/com/bobhub/chat/dto/ChatRoomResponse.java
  src/main/java/com/bobhub/chat/mapper/ChatMapper.java
  src/main/java/com/bobhub/chat/service/ChatService.java
  src/main/java/com/bobhub/comment/controller/CommentController.java
  src/main/java/com/bobhub/party/controller/PartyController.java
  src/main/java/com/bobhub/party/service/PartyService.java
  src/main/resources/mappers/ChatMapper.xml
  src/main/resources/mappers/PartyMapper.xml
  src/main/resources/mappers/PartyMemberMapper.xml
  src/main/resources/mappers/UserMapper.xml
Labels: feature
